In [4]:
import numpy as np
import cv2

cap = cv2.VideoCapture('20170518_162932.avi')

while(cap.isOpened()):
    ret, frame = cap.read()

    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

    cv2.imshow('frame',gray)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()

In [10]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

y_test, y_predicted = [] , []

y_test.append(1)
y_predicted.append(1)

y_test.append(0)
y_predicted.append(1)

y_test.append(1)
y_predicted.append(2)

y_test.append(2)
y_predicted.append(2)

cm = confusion_matrix(y_test, y_predicted)
print "confusion_matrix: \n" + str(cm)
cm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
print "Normalized confusion_matrix: \n" + str(cm)


confusion_matrix: 
[[0 1 0]
 [0 1 1]
 [0 0 1]]
Normalized confusion_matrix: 
[[ 0.   1.   0. ]
 [ 0.   0.5  0.5]
 [ 0.   0.   1. ]]


In [1]:
from sklearn import preprocessing
lb = preprocessing.LabelBinarizer()
lb.fit([1, 2, 6, 4, 2])

lb.classes_

lb.transform([1, 6])


array([[1, 0, 0, 0],
       [0, 0, 0, 1]])

In [3]:
lb.inverse_transform(lb.transform([1, 6]))

array([1, 6])

# -------------------------------- 

In [64]:
import numpy as np

x =  np.zeros([2,3])
y =  np.zeros([2,3])

y[1,:] = 1
print("x", x)
print("y", y)

x[y == 1] = 255

print("x", x)
print("y", y)

y == 1

('x', array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]]))
('y', array([[ 0.,  0.,  0.],
       [ 1.,  1.,  1.]]))
('x', array([[   0.,    0.,    0.],
       [ 255.,  255.,  255.]]))
('y', array([[ 0.,  0.,  0.],
       [ 1.,  1.,  1.]]))


array([[False, False, False],
       [ True,  True,  True]], dtype=bool)

In [ ]:
import numpy as np

def computeIoU(y_pred_batch, y_true_batch):
    return np.mean(np.asarray([pixelAccuracy(y_pred_batch[i], y_true_batch[i]) for i in range(len(y_true_batch))])) 

def pixelAccuracy(y_pred, y_true):
    y_pred = np.argmax(np.reshape(y_pred,[N_CLASSES_PASCAL,img_rows,img_cols]),axis=0)
    y_true = np.argmax(np.reshape(y_true,[N_CLASSES_PASCAL,img_rows,img_cols]),axis=0)
    y_pred = y_pred * (y_true>0)
    
    return 1.0 * np.sum((y_pred==y_true)*(y_true>0)) /  np.sum(y_true>0)